name: myposition
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  connectivity_plus: ^4.0.2
  firebase_core: ^2.16.0
  firebase_database: ^10.2.6
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  get: ^4.6.6
  google_maps_flutter: ^2.5.0
  intl: ^0.18.1
  loggy: ^2.0.3
  permission_handler: ^11.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/